version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: ps
      DB_PASSWORD: password
      DB_HOST: db

  db:
    image: postgres
    environment:
      - POSTGRESQL_USER=ps
      - POSTGRESQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:8080"
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password


  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_volume:
  tmp:
  public:
